#cloud-config
fqdn: c0.aws.bowtie.example.com
hostname: c0.aws.bowtie.example.com
preserve_hostname: false
prefer_fqdn_over_hostname: true
write_files:
- path: /etc/dex/sso.yaml
  content: |
    type: gitlab
    id: gitlab
    name: GitLab
    config:
      clientID: <clientID>
      clientSecret: <clientSecret>
      redirectURI: $DEX_ORIGIN/dex/callback
- path: /etc/bowtie-server.d/custom.conf
  content: |
    SITE_ID=<UUIDv4>
    BOWTIE_SYNC_PSK=<UUIDv4>
- path: /var/lib/bowtie/init-users
  content: |
    admin@example.com:$argon2i$v=19$m=4096,t=3,p=1$Mjl
- path: /var/lib/bowtie/skip-gui-init
- path: /etc/update-at
users:
- name: root
  ssh_authorized_keys:
  - ssh-ed25519 AAAA admin
  lock_passwd: false